[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[context.production.environment]
  VITE_APP_BASE_URL = "http://localhost:3000"
  VITE_APP_BACKEND_URL = "https://modern-maestro-backend.fly.dev"
  VITE_SPOTIFY_CLIENT_ID = "your_spotify_client_id"
  VITE_SPOTIFY_CLIENT_SECRET = "your_spotify_client_secret"
